export const TOGGLE_PRODUCT_VISIBILITY = 'TOGGLE_PRODUCT_VISIBILITY'
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT'
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_PRODUCTS = 'GET_PRODUCTS'